name: react-native-android-build-apk
on:
  push:
    branches:
      - master
      - feature/workshop-3
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Gradle Build Clean and Build Android Release
        run: |
          cd android && 
          ./gradlew clean && 
          ./gradlew cleanBuildCache && 
          ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
